<header>
    <div id="logo">
        <img src="/img/logo-topbus.png" alt="">
    </div>
    <nav id="menu">
        
    </nav>
</header>
<main>
    <section id="box-registro">
        <form action="/autenticarCompanhia" method="post">
            <h1>Olá parceiro!</h1>
            <input type="text" placeholder="E-mail" name="email">
            <input type="password" placeholder="Senha" name="senha">
            <button type="submit">logar</button>
            <button><a href="inscreverseCompanhia">Registrar-se</a></button>
            <?php if($this->view->erroAutCompanhia ==  'erro') { ?>
                <small> **Erro ao logar!! Email ou senha invalidos</small>
                <!--*** erro autenticar -->
            <?php } ?>
        </form>
    </section>
</main>
<footer id="rodape">
    
    <nav>
        <h3>Institucional</h3>
        
        <a href="">Aplicativo</a>
        <a href="">Política de Privacidade</a>
        <a href="">Termos de Uso</a>
        <a href="">Política de Cookies</a>
    </nav>
    <nav>
        <h3>Categorias</h3> 
        <a href="">Destinos</a>
        <a href="">Glossário</a>
        <a href="">Rodoviárias</a>
        <a href="">Viações</a>
    </nav>
    <nav>
        <h3>Business</h3> 
        <a href="">Programa de Afiliados</a>
        <a href="">Parcerias</a>
        <a href="">App Android</a>
        <a href="">App IOS</a>
    </nav>
    <div >
        <nav id="sac">
            <h2>  Tem duvidas? </h2>
            <a href="">🎧 Entre em contato conosco</a>
            <p>De segunda à sexta das 09h às 18h. Sábado, domingo e feriado das 09h às 16h.</p>
        </nav>
    </div>
</footer>
