<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <title>TopLine Viagens</title>
</head>
<body>
    <header>
        <div id="logo">
            <h1>logo</h1>
        </div>
        <nav id="menu">
            <a href="/entrar">Entrar</a>
            <a href="#">Sobre Nós</a>
            <a href="#">Ajuda</a>
        </nav>
    </header>
    <main>
        <section id="banner">
            <a href="/inscreverse">registra-se</a>             
        </section>
        <section id="opcoes-pagamento">
            <h3>Escolha a melhor data</h3>
            <h3>Parcele em até 3x</h3>
            <h3>Compra 100% segura</h3>
        </section>

        <section id="destino-procurados">
            <h2>Destinos mais Procurados</h2>
            <div id="mais-procurados">
                <div >
                    <h3>Para Belo Horizonte</h3>
                    <h4>Saindo De: </h4>
                    <p>Rio de Janeiro</p>
                    <p>Cabo Frio</p>
                    <p>São Paulo</p>
                </div>
                <div >
                    <h3>Para Brasília</h3>
                    <h4>Saindo De: </h4>
                    <p>Rio de Janeiro</p>
                    <p>Cabo Frio</p>
                    <p>São Paulo</p>
                </div>
                <div >
                    <h3>Para Brasília</h3>
                    <h4>Saindo De: </h4>
                    <p>Rio de Janeiro</p>
                    <p>Cabo Frio</p>
                    <p>São Paulo</p>
                </div>
                <div >
                    <h3>Para Brasília</h3>
                    <h4>Saindo De: </h4>
                    <p>Rio de Janeiro</p>
                    <p>Cabo Frio</p>
                    <p>São Paulo</p>
                </div>
            </div>
        </section>

        <section id="motivos">

            <h3><strong> Barato</strong></h3>
            <p>Viagens de ônibus por <strong> até menos da metade do preço das passagens de rodoviária.</strong>
                Sem taxas de serviços ou surpresas no pagamento. É inovação a serviço do consumidor,
                com qualidade e preço justo
            </p>
            
            <h3> <strong>Seguro</strong></h3>
            <p>
                <strong> Empresas de ônibus e motoristas certificados pela ANTT. </strong> de vida grátis e 
                ônibus com tecnologias de segurança exclusivas: câmeras de fadiga, telemetria e 
                sensores de cinto de segurança.
            </p>
            <h3><strong> Mais prático </strong></h3>
            <p>
                Você escolhe embarcar na rodoviária ou em um ponto exclusivo da Buser. Nos 
                exclusivos, você precisa apenas de um documento com foto para viajar. É só 
                reservar pelo site ou app e não precisa imprimir nada. <strong> filas, sem burocracias. </strong>
            </p>
        </section>
    </main>
    <footer id="rodape">
        Cabeçalho
    </footer>
    
</body>
</html>