<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <title>TopLine Viagens</title>
</head>
<body>
    <header>
        <div id="logo">
            <h1>logo</h1>
        </div>
        <nav id="menu">
            <a href="#">Sobre Nós</a>
            <a href="#">Ajuda</a>
        </nav>
    </header>
    <main>
        <div id="box-registro">
            <form action="/registrar" method="post">
                <input type="text" placeholder="Seu Nome" name="nome">
                <input type="text" placeholder="E-mail" name="email">
                <input type="password" placeholder="Senha" name="senha">
                <button type="submit">Inscrever-se ou logar </button>

                <?php if($this->view->erroCadastro ) { ?>

                    <small > *Erro ao tentar realizar o cadastro, verifique os campos preenchidos </small>

                <?php } ?> 
                    
            </form>
        </div>
        </main>
    <footer id="rodape">
        Cabeçalho
    </footer>
    
</body>
</html>