<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <title>TopLine Viagens</title>
</head>
<body>
    <header>
        <div id="logo">
            <h1>logo</h1>
        </div>
        <nav id="menu">
            <a href="#">Sobre Nós</a>
            <a href="#">Ajuda</a>
        </nav>
    </header>
    <main>
        <div id="box-registro">
            <form action="/registrar" method="post">
                <input type="text" placeholder="Seu Nome" name="nome">
                <input type="text" placeholder="E-mail" name="email">
                <input type="password" placeholder="Senha" name="senha">
                <button type="submit">Inscrever-se ou logar </button>

                <?php if($this->view->erroCadastro == 'existente') { ?>
                    <small > Já existe um perfil com esse e-mail, Deseja jogar ? </small>
                    <a href="/entrar">Logar</a>

                <?php } elseif($this->view->erroCadastro == 'incompleto') { ?>

                    <small > *Erro ao tentar realizar o cadastro, verifique os campos preenchidos </small>
                <?php } ?>
                <a href="#openModal">Open Modal</a>
            </form>
            
            <div id="openModal" class="modal">
                <a href="#fechar" title="Fechar" class="close">x</a>
                <form action="/registrarCampanhia" method="post">
                    <input type="text" placeholder="Razão social/Nome" name="razao">
                    <input type="text" placeholder="CNPJ" name="cnpj">
                    <input type="text" placeholder="E-mail" name="email">
                    <input type="password" placeholder="Senha" name="senha">
                    <button type="submit">Inscrever-se e Logar </button>

                    <?php if($this->view->erroCadastro == 'existente') { ?>
                        <small > Já existe um perfil com esse e-mail, Deseja jogar ? </small>
                        <a href="/entrar">Logar</a>

                    <?php } elseif($this->view->erroCadastro == 'incompleto') { ?>

                        <small > *Erro ao tentar realizar o cadastro, verifique os campos preenchidos </small>
                    <?php } ?>
                </form>   
            </div>
        </div>
        

       
        </main>
    <footer id="rodape">
        Cabeçalho
    </footer>
    
</body>
</html>