
<header>
    <div id="logo">
        <img src="/img/logo-topbus.png" alt="">
    </div>
    <nav id="menu">
        <a href="#">Sobre Nós</a>
        <a href="#">Ajuda</a>
    </nav>
</header>
<main>
    <div id="box-registro">
        <form action="/registrarCompanhia" method="post">
            <input type="text" placeholder="Razao social" name="razao">
            <input type="text" placeholder="CNPJ" name="cnpj">
            <input type="text" placeholder="E-mail" name="email">
            <input type="password" placeholder="Senha" name="senha">
            <button type="submit">Inscrever-se</button>

            <?php if($this->view->erroCadastro == 'existente') { ?>
                <small > Já existe um perfil com esse e-mail, Deseja jogar ? </small>
                <a href="/entrarCompanhia">Logar</a>

            <?php } elseif($this->view->erroCadastro == 'incompleto') { ?>

                <small > *Erro ao tentar realizar o cadastro, verifique os campos preenchidos </small>
            <?php } ?>
        </form>
    </div>
    

    
    </main>
    <footer id="rodape">
    
    <nav>
        <h3>Institucional</h3>
        
        <a href="">Aplicativo</a>
        <a href="">Política de Privacidade</a>
        <a href="">Termos de Uso</a>
        <a href="">Política de Cookies</a>
    </nav>
    <nav>
        <h3>Categorias</h3> 
        <a href="">Destinos</a>
        <a href="">Glossário</a>
        <a href="">Rodoviárias</a>
        <a href="">Viações</a>
    </nav>
    <nav>
        <h3>Business</h3> 
        <a href="">Programa de Afiliados</a>
        <a href="">Parcerias</a>
        <a href="">App Android</a>
        <a href="">App IOS</a>
    </nav>
    <div >
        <nav id="sac">
            <h2>  Tem duvidas? </h2>
            <a href="">🎧 Entre em contato conosco</a>
            <p>De segunda à sexta das 09h às 18h. Sábado, domingo e feriado das 09h às 16h.</p>
        </nav>
    </div>
</footer>
