<header>
    <div id="logo">
        <img src="/img/logo-topbus.png" alt="">
    </div>
    <nav id="menu">
        <p>Bem vindo(a) Companhia <?php print_r($_SESSION['razao']) ?></p>
        <a href="/sair">Sair</a>
    </nav>
</header>
<main>
    <section id="banner">
        <div class="cards">
            <a class="" href="#abrirModal">Cadastrar Viagem</a>
            <!-- Modal de cadastro -->
            <div id="abrirModal" class="modal">
                <div>
                    <a href="#fechar" title="Fechar" class="fechar">x</a>
                    <?php print_r($_SESSION['id']) ?>
                    <form id="cadastroViagem" action="/cadastrarViagem" method="post">
                        <input type="text" name="origem" placeholder="Origem">
                        <input type="text" name="destino" placeholder="Destino">
                        <div>
                            <span>Data da Ida:</span>
                            <input type="date" name="dataOrigem" placeholder="dataIda">                    
                        </div>
                        <div>
                            <span>Hora da saida: </span>
                            <input type="time" name="horaOrigem" >                    
                        </div>
                        <div>
                            <span>Hora da chegada: </span>
                            <input name="horaDestino" type="time">                    
                        </div>
                        <input type="number" step="0.01" name="valorPassagem" min="0.01" placeholder="Valor da Passagem"> 
                        <input type="number" name="nrPoltrona" placeholder="Quantidade de Poltronas">                                       
                        <button type="submit">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="cards">
            <h1>Dashborading de vendas</h1>
        </div>
    </section>
    <section>
    <div id="box_area_viagens">
            <?php foreach($this->view->viagens as $id_viagem => $viagem) { ?>
                <div class="box_viagem">
                    <div class="box_cidades">
                        <p>Origem: <?=$viagem['origem']?></p>
                        <p>Destino: <?=$viagem['destino']?></p>
                    </div>
                    <div class="box_data_hora">
                        <p>Data Saida: <?=$viagem['dataOrigem']?></p>
                        <p>Hora Saida: <?=$viagem['horaOrigem']?></p>
                    </div>
                </div>
            <?php }?>
        </div>
    </section>
    
</main>
<footer id="rodape">
    <nav>
        <h3>Institucional</h3>
        <a href="">Aplicativo</a>
        <a href="">Política de Privacidade</a>
        <a href="">Termos de Uso</a>
        <a href="">Política de Cookies</a>
    </nav>
    <nav>
        <h3>Categorias</h3> 
        <a href="">Destinos</a>
        <a href="">Glossário</a>
        <a href="">Rodoviárias</a>
        <a href="">Viações</a>
    </nav>
    <nav>
        <h3>Business</h3> 
        <a href="">Programa de Afiliados</a>
        <a href="">Parcerias</a>
        <a href="">App Android</a>
        <a href="">App IOS</a>
    </nav>
    <div >
        <nav id="sac">
            <h2>  Tem duvidas? </h2>
            <a href="">🎧 Entre em contato conosco</a>
            <p>De segunda à sexta das 09h às 18h. Sábado, domingo e feriado das 09h às 16h.</p>
        </nav>
    </div>
</footer>
    