<header>
    <div id="logo">
        <img src="/img/logo-topbus.png" alt="">
    </div>
    <nav id="menu">
        <p>Bem vindo(a) Companhia <?php print_r($_SESSION['razao']) ?></p>
        <div class="menu-hamburguer">
            <label for="menu-toggle" class="menu-icon">&#9776;
            <input type="checkbox" id="menu-toggle" />
            </label>
            <!-- <label for="menu-toggle" class="menu-icon">&#9776;</label> -->
            <ul class="menu" id="menu-items">
                <li><a class="buttonPrincipal" href="#abrirModal">Cadastrar Viagem</a></li>
                <li><a class="buttonPrincipal" href="#">Dashboard de Vendas</a></li>
            </ul>
        </div>
        <a class="buttonPrincipal" href="/sair">Sair</a>
      
        
    </nav>
</header>
<main>
    <section id="banner">
        <!-- Modal de cadastro -->
        <div id="abrirModal" class="modal">
            <div>
                <a href="#fechar" title="Fechar" class="fechar">x</a>
                <h2>Cadastro de Viagem</h2>
                <form id="cadastroViagem" action="/cadastrarViagem" method="post">
                    <div>
                        <input type="text" name="origem" placeholder="Origem">
                        <input type="text" name="destino" placeholder="Destino">                        
                    </div>                    

                    <div>
                        <span>Data da Ida:</span>
                        <input type="date" name="dataOrigem" placeholder="dataIda">   
                    </div>
                    
                    <div>
                        <span>Hora da saida: </span>
                        <input type="time" name="horaOrigem">                    
                    </div>
                    <div>
                        <span>Hora da chegada: </span>
                        <input name="horaDestino" type="time">                    
                    </div>
                    <div>
                        <input type="number" step="0.01" name="valorPassagem" min="0.01" placeholder="Valor da Passagem"> 
                    </div>
                    <div>
                        <input type="number" name="nrPoltrona" placeholder="Quantidade de Poltronas"> 
                    </div>
                    
                    <div class="button-container">
                        <button  class="button-container" type="submit">Cadastrar</button>
                    </div>                     
                </form>
            </div>
        </div>
    </section>
    <section>
        <div id="Mensagem">
            <?php if ($this->view->mensagemEdicao == "editado") { ?>
                <small>Viagem Editada!</small>
            <?php } elseif($this->view->mensagemEdicao == "apagado") { ?>            
                <small>Viagem Apagada!</small>
            <?php } ?>
            <?php $_GET['mensagemEdicao'] = "TESTE";?>
        </div>
        <h1>Viagens Programadas</h1>
        <div id="box_area_viagens">
                
            <?php foreach($this->view->viagens as $id_viagem => $viagem) { ?>
                <div class="box_viagem">
                    <div class="box_cidades">
                        <p>Origem: <?=$viagem['origem']?></p>
                        <p>Destino: <?=$viagem['destino']?></p>
                    </div>
                    <div class="box_data_hora">
                        <p>Data Saida: <?=$viagem['dataOrigem']?></p>
                        <p>Hora Saida: <?=$viagem['horaOrigem']?></p>
                        <p>cod: <?=$viagem['id']?></p>
                    </div>
                    <div class="box_alterar">
                        <a href="apagarViagem?id=<?=$viagem['id']?>">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </a>
                        <a href="EditarViagemPag?id=<?=$viagem['id']?>">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>   
                    </div>
                </div>
            <?php }?>
        </div>

    </section>
    
</main>
<footer id="rodape">
    <nav>
        <h3>Institucional</h3>
        <a href="">Aplicativo</a>
        <a href="">Política de Privacidade</a>
        <a href="">Termos de Uso</a>
        <a href="">Política de Cookies</a>
    </nav>
    <nav>
        <h3>Categorias</h3> 
        <a href="">Destinos</a>
        <a href="">Glossário</a>
        <a href="">Rodoviárias</a>
        <a href="">Viações</a>
    </nav>
    <nav>
        <h3>Business</h3> 
        <a href="">Programa de Afiliados</a>
        <a href="">Parcerias</a>
        <a href="">App Android</a>
        <a href="">App IOS</a>
    </nav>
    <div >
        <nav id="sac">
            <h2>  Tem duvidas? </h2>
            <a href="">🎧 Entre em contato conosco</a>
            <p>De segunda à sexta das 09h às 18h. Sábado, domingo e feriado das 09h às 16h.</p>
        </nav>
    </div>
</footer>
<script>

document.addEventListener("DOMContentLoaded", function() {
  const menuToggle = document.getElementById("menu-toggle");
  const menuItems = document.getElementById("menu-items");

  menuToggle.addEventListener("change", function() {
    if (menuToggle.checked) {
      menuItems.style.display = "block";
    } else {
      menuItems.style.display = "none";
    }
  });
});




</script>
    