<html>
	<head>
		<!-- width=device-width-> para atribuir que a largura da pagina deve ser igual a largura do dispositivo 
		initial-scale -> o nivel initial do zoom deve ser 1  -->
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<meta charset="utf-8" />
		<title>TopBus Viagens</title>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<link rel="stylesheet" type="text/css" href="/css/style.css">
		
		<script src="https://kit.fontawesome.com/cecdc256ba.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		
		
	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>